### PR TITLE
added scan unifier to bringup layer

### PR DESCRIPTION
**Pull request by benmaidel**
launch the scan unifier by default

related PRs:
ipa320/cob_driver#246
ipa320/ipa_navigation#84
ipa320/cob_navigation#56

### CODE REVIEW

**Comment by benmaidel** [comment]
tested on cob4-2: scan unifier starts as expected

**Comment by NadiaHG** [comment]
LGTM

**Comment by mgruhler** [comment]
LGTM

**Comment by fmessmer** [comment]
I know this is nit-picking...
...but wouldn't it make more sense to add the scan_unifier.launch lines just under the sick_s300.launch section?
...do really all robots need the scan_unifier? Or just those using ipa_navigation? (CPU consumption?)

**Comment by benmaidel** [comment]
Imagine we use a new Laserscanner, then we need extra work to add the scan unifier to the new launch files.

**Comment by fmessmer** [comment]
Formal Review OK
As PR #365 came later, the launch file for `cob4-3` should be added in #365

**Comment by floweisshardt** [comment]
Missing dependency in cob_bringup/package.xml (will be fixed after merging by @ipa320/owners

**Pull request merged**
