### PR TITLE
Remove sound play buttons and fix behaviours

### PR DESCRIPTION
**Pull request by floweisshardt**
extends #597

### CODE REVIEW

**Comment by fmessmer** [comment]
I merged this into #411 
Could someone with a proper setup test my branch [fix_handle_wait_pick_behavior](https://github.com/ipa-fxm/cob_robots/tree/fix_handle_wait_pick_behavior), i.e. pick-with-handles, on the robot?

**Review by NadiaHG — APPROVED** [review]

**Comment by floweisshardt** [comment]
tested on cob4-7: OK

**Comment by fmessmer** [comment]
#411 includes all of these commits but rebases on indigo_dev for a cleaner commit history...
In case you merge this, we will have merge conflicts in #411 again...

Even more so, see my comment https://github.com/ipa320/cob_robots/pull/591/files#r97415187
which is fixed in #411...so if #411 works...we should merge #411 instead of this one here

**Comment by fmessmer** [comment]
travis will be fixed after #602 is merged

**Comment by NadiaHG** [comment]
please solve the merge conflict

**Comment by floweisshardt** [comment]
merge conflict solved

**Comment by ipa-fxm** [comment]
**Definitely rebase!!!**

**Review by fmessmer — DISMISSED** [review]
**Definitely rebase!!!**

**Comment by benmaidel** [comment]
This PR is too big! Also the PR description is wrong!

**Pull request merged**
