### PR TITLE
canopen configs for old base cob4-1 and cob4 2

### PR DESCRIPTION
**Pull request by fmessmer**
supersedes #405 
requires https://github.com/ipa320/cob_driver/pull/258 - **merge with ipa320/cob_driver (indigo_dev)**

### CODE REVIEW

**Comment by fmessmer** [comment]
tested on cob4-1 and in simulation

Are there any more things that need to be adjusted due to the new base driver?
Any action_names, service_names, parameters, config...?

**Comment by floweisshardt** [comment]
I don't think so because we were already using the new namespaces with the old driver

**Comment by mathias-luedtke** [comment]
~~`cob_bringup` needs to `exec_depend` on `cob_omni_drive_controller`.~~

**Comment by fmessmer** [comment]
I think the `exec_depend` to `cob_omni_drive_controller` is not required within `cob_bringup` - it already is included in `cob_hardware_config` (there the controller plugin is mentioned in the yaml).

**Comment by mathias-luedtke** [comment]
Seems legit :)

**Comment by floweisshardt** [comment]
opend issue for handling different canX.yaml configurations for different components, see https://github.com/ipa320/cob_robots/issues/420

**Comment by NadiaHG** [comment]
Test on cob4-2: OK

**Comment by floweisshardt** [comment]
CR: OK

**Pull request merged**
