### PR TITLE
use xacro --inorder + move gazebo_ros_control plugin to component

### PR DESCRIPTION
**Pull request by fmessmer**
These PR-set allows to use latest [xacro](http://wiki.ros.org/action/fullsearch/xacro), i.e. e.g. conditional blocks

Also moves the per-component gazebo_ros_control plugin from the robot to the component. This is another step towards the robot-module-component structure we are tackling...

Related PRs are:
 - https://github.com/ipa320/cob_common/pull/208
 - https://github.com/ipa320/cob_manipulation/pull/97
 - https://github.com/ipa320/cob_control/pull/130
 - https://github.com/ipa320/schunk_robots/pull/72
 - https://github.com/ipa320/schunk_modular_robotics/pull/181
 - https://github.com/ipa320/cob_simulation/pull/136

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
What is the matter with the last commit?
I prefer lowercase true/false.

**Comment by fmessmer** [comment]
me, too...but it's because of lines like [this one](https://github.com/ipa320/cob_common/pull/208/files#diff-7a500bdef900893334795e9776e14b01R145) where I use [conditional blocks](http://wiki.ros.org/action/fullsearch/xacro#Conditional_Blocks) that need to be pure python....i.e. False/True...it's a bummer

**Comment by mathias-luedtke** [comment]
The documentation says: "The expression needs to evaluate to "0", "1", "true", or "false", otherwise an error will be thrown.", so this should still work somehow.
If not, it is a regression bug, which needs to be reported.
It might have even be fixed, but wasn't backported to indigo..

Simple fix:
```
<xacro:if value="${active}=='true'">
```
or
```
<xacro:if value="'${active}'">
```

**Comment by fmessmer** [comment]
I opened an issue: https://github.com/ros/xacro/issues/145
Let's see what the comments are...
Otherwise, I will test one of @ipa-mdl's proposed workarounds...

**Comment by fmessmer** [comment]
Affects https://github.com/ipa320/cob_common/pull/208 and this PR + https://github.com/ipa320/schunk_modular_robotics/pull/181 which already has been merged

**Comment by fmessmer** [comment]
https://github.com/ipa320/cob_common/pull/208 is updated using @ipa-mdl's workaround:
 > `<xacro:if value="${(dof1 == 'true') or (dof2 == 'true') or (dof3 == 'true')}">`

Thus, `True`/`False` is reverted in this PR and for https://github.com/ipa320/schunk_modular_robotics/pull/181 `True`/`False` is reverted in https://github.com/ipa320/schunk_modular_robotics/pull/182

**Pull request merged**
