### PR TITLE
switch back to python version of hz monitor

### PR DESCRIPTION
**Pull request by floweisshardt**
fallback solution for ipa320/msh#767
currently testing on feature branch on paul-ingolstadt...

### CODE REVIEW

**Review by benmaidel — APPROVED** [review]

**Review by fmessmer — DISMISSED** [review]
fine with me if it works better...
still I would like to debug the diagnostic_updater-based implementation in ipa320/msh#767

**Review by fmessmer — CHANGES_REQUESTED** [review]
according to @ipa-fmw the problem with the hz_monitor was rather a ntp/TimeSync issue on the cob-pcs....thus, I vote for keeping the diagnostic_updater-based c++ implementation....

only `diagnostic_aggregator.yaml` needs to be adjusted...

**Comment by fmessmer** [comment]
I created a new issue for fixing the diagnostic_aggregator groups of the c++-based hz_monitor in #676 

@ipa-fmw 
what implementation is currently used on Paul? python-based as a feature branch?

**Comment by floweisshardt** [comment]
we're currently using python-based from indigo_dev

**Comment by fmessmer** [comment]
indigo_dev uses c++-based topic_status_monitor: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/tools/hz_monitor.launch#L9

**Comment by fmessmer** [comment]
I assume we can close this PR **unmerged** as soon as https://github.com/ipa320/cob_robots/issues/676 is fixed

**Comment by fmessmer** [comment]
As there is no easy fix for #676 (see my https://github.com/ipa320/cob_robots/issues/676#issuecomment-315174055), I guess we can merge this PR...

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
