### PR TITLE
Corrected odometry topic remapping, error done in 8868a5c

### PR DESCRIPTION
**Pull request by destogl**

### CODE REVIEW

**Comment by fmessmer** [comment]
This seems to have slipped through...I guess `odometry_controller/odometry` is correct!
Can you also change it [here](https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/controllers/base_controller_plugin.launch#L30) and [here](https://github.com/ipa320/cob_robots/blob/11e9d9f796be0be23e27d1c2498514754976fd3b/cob_bringup/tools/velocity_smoother.launch#L15) please?

@ipa-bnm @ipa-mig please verify (and find more occurences...:wink:)

**Comment by mgruhler** [comment]
Seems correct.

**Comment by destogl** [comment]
@ipa-fxm done! Grep doesn't fined any occurences more...

**Comment by fmessmer** [comment]
FR OK...anyone tested it on hardware?

**Comment by NadiaHG** [comment]
FR: OK

**Comment by fmessmer** [comment]
merging now

**Pull request merged**
