### PR TITLE
modified travis config to build with source overlays

### LINKED ISSUE #374: Add launch file checks and URDF checks
We need to write these tests and add them to travis

@ipa-fmw @ipa-mdl 
Do you have a good idea how to deal with the problem about using `$(find )` and `$(arg )` and such mixed together?

### PR DESCRIPTION
**Pull request by mathias-luedtke**
closes #374

### CODE REVIEW

**Comment by floweisshardt** [comment]
looks good on travis. As soon as we have reasonable tests defined, we should unkomment 'catkin_test_results' to reflect the test result status in the travis log. @ipa-mdl: Thanks!

**Comment by mathias-luedtke** [comment]
There is an issue with the latest `catkin` version that results in many cmake errors/warnings (https://github.com/ros/catkin/issues/761).

**Comment by mathias-luedtke** [comment]
Functionality was successfully tested in #378.

@ipa-fxm, @ipa-fmw: your turn :D

**Comment by fmessmer** [comment]
Awesome!
The run_test failures detected in #378 are fixed in https://github.com/ipa320/cob_robots/pull/379

I assume, we now should apply the same `.travis.yml` and `.travis.rosinstall` to all the other repos, too?
(Note that in the `.travis.rosinstall`, entries for all bringup repos should be included **except for the respective repo itself** - as explained by @ipa-mdl)

**Comment by mathias-luedtke** [comment]
> Note that in the .travis.rosinstall, entries for all bringup repos should be included except for the respective repo itself

The respective repo can be included, but it will be build twice then.
If you don't bundle a `.travis.rosinstall` file the default one is used (https://github.com/ipa320/setup/blob/master/repositories/cob_indigo_bringup.rosinstall).

**Comment by fmessmer** [comment]
Of course....travis.rosinstall is installed in an underlay...
We should definitely update the default .rosinstall file in setup according to the changes in https://github.com/ipa-fxm/cob_robots/commit/edf9f96a78168ab8c7e3cf1fd18f1da205e4f21d (then we might be able to just use that one)

**Comment by floweisshardt** [comment]
CR: OK

**Pull request merged**
