### PR TITLE
restructure canopen driver yamls and remove canX yamls

### LINKED ISSUE #420: remove canX.yaml files and integrate into component specific yaml files
currently can0.yaml is used on the base pc for the base and on the torso pc for the arms/sensorring/torso. If we keep a common can0.yaml we cannot have different CAN configurations for e.g. base and torso.

@ipa-mdl had some suggestion how to restructure

### PR DESCRIPTION
**Pull request by fmessmer**
fixes #420 according to @ipa-mdl's concept

I did not adjust the driver.yaml's of:
- raw3-3
- raw3-6
  as they still use the old ipa_canopen config layout in there respective yaml file and we do not have access to the hardware....

### CODE REVIEW

**Comment by floweisshardt** [comment]
FR: OK

**Comment by fmessmer** [comment]
After merging this, we should switch the `interval_ms` back from 10 to 20 in all `base_driver.yamls` in order to gain the control frequency of 50Hz...that has been used by the old undercarriage_ctrl driver (see [here](https://github.com/ipa320/cob_driver/blob/indigo_dev/cob_undercarriage_ctrl/ros/src/cob_undercarriage_ctrl.cpp#L135))

**Comment by floweisshardt** [comment]
tested on cob4-2: OK (setting interval_ms to 20 seems to solve shaking behaviour)

**Comment by fmessmer** [comment]
> (setting interval_ms to 20 seems to solve shaking behaviour)

See my [comment](https://github.com/ipa320/cob_robots/pull/441#issuecomment-188218048) in #441

**Pull request merged**
