### PR TITLE
Grouped low level components

### PR DESCRIPTION
**Pull request by mathias-luedtke**
This PR is a rebased version of #574 with only simple sublitutions of common low-level component launch code.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
The tests keep failing because of ~~https://github.com/ipa320/care-o-bot/issues/34~~ https://github.com/ipa320/cob_calibration_data/pull/113

**Comment by NadiaHG** [comment]
travis is happy now! thanks @ipa-mdl

**Comment by mathias-luedtke** [comment]
I have implemented a little helper script to test the result: https://gist.github.com/ipa-mdl/66b14a895e13003a2f76e483bd00aa63
It dumps the complete launch file to XML.

**Comment by mathias-luedtke** [comment]
closing in favour of #583

**Pull request closed without merging**
