### PR TITLE
update moveit config for all robots

### PR DESCRIPTION
**Pull request by fmessmer**
This is just to not forget to do this now that the moveit_config structure has been updated...

 - re-run once new mesh for the cob4_torso (see https://github.com/ipa320/cob_manipulation/issues/89) is available
 - add cob4-5 as requested https://github.com/ipa320/cob_robots/pull/573#discussion_r93009286
 - other robots without an moveit_config: cob4-3, cob4-4, cob4-5, cob4-6, raw3-2, raw3-3, raw3-4, raw3-5, raw3-6
 - @ipa-bfb has an updated description + hardware_config for latest raw3-1 setup and an updated moveit_config for it

### CODE REVIEW

**Review by NadiaHG — APPROVED** [review]

**Comment by fmessmer** [comment]
rebased onto #588

**Comment by fmessmer** [comment]
update this wrt #600

**Comment by fmessmer** [comment]
I updated this wrt #600, but let me rebase after #588 is merged and before merging this!

**Comment by fmessmer** [comment]
rebase after #602 is merged

**Pull request merged**
