### PR TITLE
Twist controller and lwa4p_extended fixes

### PR DESCRIPTION
**Pull request by fmessmer**
for testing with cob4 hardware

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-fmw-ms will test it on the hardware
wait for his feedback

**Comment by ipa-fmw-ms** [comment]
Working but not recommended since the existence of unsolved Singularities and the Torso itself is unstable and minimal movement causes power loss and reboot.

**Comment by floweisshardt** [comment]
we'll wait for singularity bug to be fixed first

**Comment by fmessmer** [comment]
unfortunately, I did not open a new feature branch for the previous commits....
however, I commented the twist_controller in cob_bringup/cob4-1.xml launch file so that it is not used

new features are:
- increased timeouts for the controller_manager/spawner
- fixed the lwa4p_extended model see also PR on schunk_modular_robotics (see https://github.com/ipa320/schunk_modular_robotics/pull/95)
- some PID tuning scripts

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by floweisshardt** [comment]
visual review: OK

**Pull request merged**
