### PR TITLE
[cob4-2] New torso pcs

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
test on cob4-2: OK

**Comment by floweisshardt** [comment]
CR: OK

**Comment by fmessmer** [comment]
should we consider sym-links for the cob4-1 files in this particular situation, i.e. cob4-1 = cob4-2_without_arms?

**Comment by floweisshardt** [comment]
I would avoid symlinks here as we might have some modules (e.g. sensorring) which are different between cob4-1 and cob4-2 in the future.

**Comment by fmessmer** [comment]
I only meant symlinks for the pc-monitor files modified in this PR...

**Comment by fmessmer** [comment]
my comments are considered in #408

**Comment by fmessmer** [comment]
unfortunately, we do not benefit from symlinks...it's still ugly...so we keep this suggestion

**Comment by fmessmer** [comment]
travis is happy

**Pull request merged**
