### PR TITLE
added bms driver to bringup

### PR DESCRIPTION
**Pull request by NadiaHG**
This pull request can not be merge until cob_bms_driver is publicly available.

### CODE REVIEW

**Comment by fmessmer** [comment]
FR ok

**Comment by floweisshardt** [comment]
FR: OK

**Comment by floweisshardt** [comment]
for merging we should wait until cob_bms_driver is available and travis is happy

**Comment by fmessmer** [comment]
travis should be restarted after https://github.com/ipa320/cob_driver/pull/270 is merged

**Comment by floweisshardt** [comment]
https://github.com/ipa320/cob_driver/pull/270 is merged now, only waiting for travis

**Pull request merged**
