### PR TITLE
Cleanup teleop parameters (unused button parameters)

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
Please merge this PR after the https://github.com/ipa320/cob_robots/pull/414

**Comment by fmessmer** [comment]
can you pull from ipa320/indigo_dev again?

**Comment by NadiaHG** [comment]
@ipa-fxm done!

**Comment by fmessmer** [comment]
FR ok

**Comment by floweisshardt** [comment]
travis was not triggered for this PR (due to yesterdays travis outtake).

@ipa-nhg: Please close and reopen or add a commit to retrigger travis.

**Comment by floweisshardt** [comment]
FR: OK

**Comment by fmessmer** [comment]
you can also do a `git rebase origin-320/indigo_dev` and `git push -f origin TeleopClean`

**Comment by NadiaHG** [comment]
Thanks @ipa-fxm. Travis triggered again the job

**Comment by fmessmer** [comment]
FR ok...however, we need to take care with PRs modifying any yaml within `cob_hardware_config` due to #426

**Comment by fmessmer** [comment]
merging

**Pull request merged**
