### PR TITLE
delete old and unused base velocity smoother config

### PR DESCRIPTION
**Pull request by floweisshardt**
is replaces by velocity_smoother.yaml using new smoother implementation

### CODE REVIEW

**Comment by fmessmer** [comment]
FR ok

Should we put one of the yaml's into the cob_base_velocity_smoother` package as an example config?

**Comment by mgruhler** [comment]
FR ok

+1 for putting one example yaml in the package.

**Comment by NadiaHG** [comment]
FR: OK

**Comment by floweisshardt** [comment]
-1 for putting an example config in the package
+1 for documenting all parameters on the wiki page http://wiki.ros.org/cob_base_velocity_smoother?distro=indigo

**Comment by fmessmer** [comment]
Then we also would need to clarify that now there are two base_velocity_smoother implementations within the cob_base_velocity_smoother package...and explain their parameterization respectively!

**Comment by fmessmer** [comment]
I did the according update on the wiki

**Pull request merged**
