### PR TITLE
Test for failure

### PR DESCRIPTION
**Pull request by mathias-luedtke**

### CODE REVIEW

**Comment by benmaidel** [comment]
FR: :ok:
except my one change in here :smile:

**Comment by mathias-luedtke** [comment]
Before fix:

```
$ catkin_test_results
build/test_results/cob_bringup/roslaunch-check_robots_cob3-9.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_bringup/roslaunch-check_robots_cob4-2.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_bringup/roslaunch-check_robots_raw3-1.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_bringup/roslaunch-check_robots_raw3-3.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_controller_configuration_gazebo/roslaunch-check_launch_robots_default_controllers_cob4-1.launch.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_controller_configuration_gazebo/roslaunch-check_launch_robots_default_controllers_cob4-2.launch.xml: 1 tests, 0 errors, 1 failures
Summary: 62 tests, 0 errors, 6 failures
```

**Comment by mathias-luedtke** [comment]
After the fix:

```
$ catkin_test_results
build/test_results/cob_bringup/roslaunch-check_robots_cob3-9.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_bringup/roslaunch-check_robots_cob4-2.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_bringup/roslaunch-check_robots_raw3-3.xml.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_controller_configuration_gazebo/roslaunch-check_launch_robots_default_controllers_cob4-1.launch.xml: 1 tests, 0 errors, 1 failures
build/test_results/cob_controller_configuration_gazebo/roslaunch-check_launch_robots_default_controllers_cob4-2.launch.xml: 1 tests, 0 errors, 1 failures
Summary: 62 tests, 0 errors, 5 failures
```

**Comment by mathias-luedtke** [comment]
Test succeeded.

**Pull request closed without merging**
