### PR TITLE
Enable collision monitor

### PR DESCRIPTION
**Pull request by fmessmer**
Now that torso mesh is fixed and collision matrix is updated, we could test the collision_monitor again...
Please test on robot before merging

### CODE REVIEW

**Comment by fmessmer** [comment]
FIXME: closing xml tag is wrong...

**Comment by fmessmer** [comment]
travis will be fixed after #602 is merged

**Comment by fmessmer** [comment]
https://github.com/ipa320/cob_robots/pull/581 is merged...collision_monitor needs to be tested on hardware/simulation

**Comment by fmessmer** [comment]
@ipa-nhg 
rebased and ready for testing on cob4-5

**Comment by fmessmer** [comment]
I get an 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range
[cob_collision_monitor_node-18] process has died [pid 28862, exit code -6, cmd /home/fxm/projects/indigo/care-o-bot/devel/lib/cob_collision_monitor/cob_collision_monitor_node /cob_collision_monitor_node/state_is_valid:=/safety_controller/state_is_valid __name:=cob_collision_monitor_node __log:=/home/fxm/.ros/log/eebacbb6-3bcd-11e7-86e7-0024bed884cf/cob_collision_monitor_node-18.log].
log file: /home/fxm/.ros/log/eebacbb6-3bcd-11e7-86e7-0024bed884cf/cob_collision_monitor_node-18*.log
```
when using it in simulation...investigating...

I think it's a race condition with `clock` and `/use_simtime` related to this lines https://github.com/ipa320/cob_manipulation/blob/indigo_dev/cob_collision_monitor/src/collision_monitor_node.cpp#L21-L23
as it works fine to run the launch file separately after gazebo is up...

@ipa-mdl FYI

**Comment by fmessmer** [comment]
exception handling is added in https://github.com/ipa320/cob_manipulation/pull/114

**Comment by NadiaHG** [comment]
as seen on cob4-5, the current meshes cause collisions even in acceptable configurations, e.g. within the cob4_hand (`gripper_right_finger_2_link` and `gripper_right_grasp_link`)....also the torso_center_link is using an enlarged collision mesh which causes collisions in certain default configuration, e.g. side...

thus, we would need to rework the meshes...

**Comment by NadiaHG** [comment]
also there are configurations that lead to collision on hardware while geometric model is ok, i.e. `state_valid==true`

this is a matter of calibration!

head_shoulder_collision

**Comment by ipa-rmb** [comment]
Still relevant or close?

**Pull request closed without merging**
