### PR TITLE
[kinetic] use industrial_ci for travis

### PR DESCRIPTION
**Pull request by benmaidel**

### CODE REVIEW

**Comment by benmaidel** [comment]
@ipa-fmw @ipa-fxm @ipa-nhg 
If we would like to proceed migration to kinetic we should probably just merge some kinetic pr's. This one will not succeed until: A all depended packages are released or B all depended packages are inserted into .travis.rosinstall

What do you think? How should we proceed? 
Merge it or add all dependencies to .travis.rosinstall

**Comment by floweisshardt** [comment]
I'd vote to wait with a release until we've tested on (some) HW and in the meanwhile add all not released dependencies to the rosinstall file.

**Comment by fmessmer** [comment]
add to .rosinstall file would be ok...as we definitely should test on hardware before releasing...(it won't be long, though :wink:)

**Comment by fmessmer** [comment]
@ipa-bnm 
do you also plan on merging `indigo_dev` to `kinetic_dev` for all repos...or are you quite up to date?

(see https://github.com/ipa320/cob_robots/compare/kinetic_dev...indigo_dev?expand=1)

**Comment by benmaidel** [comment]
sure, someday we have to merge our `indigo_dev` changes to `kinetic_dev`

**Comment by fmessmer** [comment]
I will merge all [kinetic]-tagged PRs before cleaning up branches...

**Pull request merged**
