### PR TITLE
Feature/zr300

### PR DESCRIPTION
**Pull request by fmessmer**
rebases #692

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-jba @ipa-fez @ipa-fmw 
good to merge now?
(https://github.com/intel-ros/realsense/pull/244 has been merged...though https://github.com/intel-ros/realsense/pull/259 is still pending - but minor)

**Review by floweisshardt — DISMISSED** [review]

**Comment by ipa-fez** [comment]
just for my understanding: if we merge this,  we can't release until realsense is released, right?

**Comment by fmessmer** [comment]
> just for my understanding: if we merge this, we can't release until realsense is released, right?

I think so...unfortunately, those guys are not too responsive to github issues/PRs...

**Review by ipa-fez — CHANGES_REQUESTED** [review]
Depending on when we want to release again (we released this not too long ago AFAIK) this might be OK to merge but I want to hear @ipa-jba's opinion first.

**Comment by fmessmer** [comment]
simply rebased - no additional changes...still waiting for @ipa-jba

**Comment by fmessmer** [comment]
ping @ipa-jba 
I also asked for a new release of realsense in https://github.com/intel-ros/realsense/issues/267

**Pull request merged**
