### PR TITLE
added 10 Hz heartbeat to Schunk DCF

### LINKED ISSUE #580: Enable heartbeat producer for Schunk arms
Speeds up init

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Will speedup initialization, closes #580.
@ipa-tif: FYI

### CODE REVIEW

**Review by NadiaHG — APPROVED** [review]
Tested on the hardware?

**Comment by mathias-luedtke** [comment]
Only on LWA4D, not Care-O-bot.

**Comment by fmessmer** [comment]
@ipa-nhg @ipa-mdl 
Could you test this on the cob's while we have them here...in order to finalize/merge this PR?

**Comment by mathias-luedtke** [comment]
rebased.

**Review by floweisshardt — APPROVED** [review]
finally tested on HW: OK (done @cob4-kist)

**Comment by destogl** [comment]
Sorry for commenting on closed PR...

Why not add this into schunk_robots repository?

**Comment by floweisshardt** [comment]
schunk_robots is just includes example packages for schunk hardware. our configuration with cob/raw is in cob_robots

**Comment by fmessmer** [comment]
@destogl please feel free to add/test this with schunk_robots....we are currently not using that repo much at ipa anymore...

**Comment by destogl** [comment]
@ipa-fxm you mean you do not use it in terms of parameters or at all? Since to my understanding you have Schunk-arms on Care-O-Bot :D

I will test it with our robot... Thanks!

**Comment by fmessmer** [comment]
we do use the Schunk arms with cob...that's why we added the parameter to cob_robots

we don't use the arms stand-alone...that's why we did not add it to schunk_robots...

**Pull request merged**
