### PR TITLE
corrected light_configuration.yaml

### PR DESCRIPTION
**Pull request by benmaidel**

### CODE REVIEW

**Comment by floweisshardt** [comment]
LGTM

**Comment by fmessmer** [comment]
Could you please apply this fix to the other robots, too? Thanks!
- cob3-2
- cob3-6
- cob3-9
- cob4-2

**Comment by benmaidel** [comment]
this do only apply to raw3-3, so no need to change it for other robots

**Comment by fmessmer** [comment]
Ok, thanks...merging...

**Pull request merged**
