### PR TITLE
params for battery capacity calculation added

### PR DESCRIPTION
**Pull request by timhappy**
requires ipa320/cob_driver#278

### CODE REVIEW

**Comment by mgruhler** [comment]
CR: ok

**Comment by benmaidel** [comment]
CR: ok

**Comment by floweisshardt** [comment]
I'd like to avoid adding this parameters at all. Even if we follow up on the phidget solution we should be able to calculate a relative_ramaining_capacity in percent, so no need to get down to the voltage level here.

**Comment by floweisshardt** [comment]
this PR is not relevant any more because we're using the phidget based power state publisher which calculates a relative_remaining_capacity

**Pull request closed without merging**
