### PR TITLE
Fix travis run tests

### PR DESCRIPTION
**Pull request by fmessmer**
builds on top of #375 
fixes run_tests as detected in #378

### CODE REVIEW

**Comment by fmessmer** [comment]
The missing install tag for `cob_obstacle_distance/test_interactive_obstacle_node.py` have been added in https://github.com/ipa320/cob_control/pull/68

**Comment by mathias-luedtke** [comment]
You can restart the travis job as soon as https://github.com/ipa320/cob_control/pull/68 was merged.
As an alternative you can temporally switch the repo/branch in the rosinstall file.

**Comment by floweisshardt** [comment]
just restarted travis (https://travis-ci.org/ipa320/cob_robots/builds/92419241), let's wait for the result...

**Comment by floweisshardt** [comment]
travis is happy, so am I

**Pull request merged**
