### PR TITLE
upgrade cob4-2

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Review by NadiaHG — APPROVED** [review]

**Comment by mathias-luedtke** [comment]
test fails actually

**Comment by fmessmer** [comment]
So this is previous cob4-1 config adjusted to latest hardware composition, i.e. enable head and sensorring, renamed to cob4-2 and cleaned up, i.e. removed all arm/gripper left-overs?

After merging this, everything related to cob4-1 should be obsolete and removed, right?

**Comment by fmessmer** [comment]
merging this requires updating moveit_config #581 as the URDF changed....

**Comment by floweisshardt** [comment]
right, after cob4-2 is setup properly we should remove all cob4-1 related config. cob4-1 will no longer exist. this needs to be done in cob_robots, cob_calibration_data, cob_manipulation, cob_navigation and msh.

tested on cob4-2: OK
@ipa-fxm: ok to merge?

**Review by fmessmer — APPROVED** [review]
I'd say so

**Pull request merged**
