### PR TITLE
Updated base solo

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
needs https://github.com/ipa320/cob_robots/pull/395

**Comment by NadiaHG** [comment]
test on cob4-2: OK

**Comment by floweisshardt** [comment]
CR: OK

**Comment by mgruhler** [comment]
Where is the stuff from `base_collision_observer.launch` now started?

**Comment by floweisshardt** [comment]
this is only for the base_solo case which is a recovery mode if the complete robot bringup cannot be startet. Thus there's no need to launch the base_collision_observer here.
The base_collision_observer is still launched in the robot.xml files (complete bringup)

**Comment by mgruhler** [comment]
Right, makes sense! Fine for me then.

**Comment by fmessmer** [comment]
but why not keep it - at least commented out (as it is done for cob4's)?

**Comment by fmessmer** [comment]
Ok, accepted...merging

**Pull request merged**
