### PR TITLE
[Indigo] Indigo hardware updates

### PR DESCRIPTION
**Pull request by fmessmer**
includes #278 

adjusts/restructures launch files in cob_bringup (robot hardware) to new namespaces

merge together with:
- https://github.com/ipa320/schunk_modular_robotics/pull/132
- https://github.com/ipa320/cob_driver/pull/210
- https://github.com/ipa320/cob_control/pull/27

### CODE REVIEW

**Comment by fmessmer** [comment]
catkin_make test pass (except for deprecation warning)

the following drivers will not be ported to new namespace structure:
- frida
- prace_grippers
- lbr
- ur

all other components/robots should now be using the new namespace structure

**Comment by floweisshardt** [comment]
fixes #279

**Comment by floweisshardt** [comment]
fixes #115

**Comment by fmessmer** [comment]
tested on raw3-1 hardware...

@abubeck FYI

**Comment by fmessmer** [comment]
tested on cob4-2 hardware...

only problem is that in [cob4_base.urdf.xacro](https://github.com/ipa320/cob_common/blob/indigo_dev/cob_description/urdf/cob4_base/base.urdf.xacro#L78) the suffixes already have been adjusted to the joint names of cob4-6....but cob4-1 and cob4-2 use old [base_driver.launch](https://github.com/ipa-fxm/cob_robots/blob/indigo_dev/cob_bringup/drivers/base_driver.launch) which cannot handle [fl, b, fr] suffixes but only [fl, bl, br]....

**Comment by fmessmer** [comment]
waiting for comments....

...or cob3-2...:wink:

**Comment by floweisshardt** [comment]
visual review: Ok (although it is hard to judge if that will work on all robots)

**Comment by fmessmer** [comment]
after merge conflicts, this PR is reopened in #282

**Pull request merged**
