### PR TITLE
Separation of driver and controller (yaml + launch)

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by fmessmer** [comment]
all changes carried out for every robot affected (cob3's, cob4's, raw's, desire)

needs to be tested with hardware!

The concept of separation does not hold smoothly for the components where the driver also provides controller interfaces (e.g. frida, head_axis, prace_grippers, schunk_sdh, ur)

**Comment by floweisshardt** [comment]
- add controller directory containing pure controllers (for the moment that's only trajectory_controller.launch)
- add an argument controller with default="" to component_solo.launch
- rename schunk_powercube_chain.launch to schunk_powercube_chain_driver.launch

**Comment by floweisshardt** [comment]
- rename voltage_controller.launch to battery_voltage.launch
- rename voltage_filter.launch to batter_voltage_filter.launch

**Comment by fmessmer** [comment]
all cob_bringup tests passed!

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by fmessmer** [comment]
latest commits include:
- component_solo for canopen components
- several merges with raw3-3 development (e.g. #185, #187)

tested with raw3-3 hardware

one remaining issue is still 
whether the parameter module_ids: [] from X_driver.yaml in cob_hardware_config
is required by canopen_driver.launch

**Comment by NadiaHG** [comment]
Visual Review: OK

**Pull request merged**
