### PR TITLE
deleted unsupported robots

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by floweisshardt** [comment]
visual review: OK --> please wait for decision on unsupported robots before merging

**Comment by floweisshardt** [comment]
summary of discussions:
- we'll keep all raws
- we'll delete desire
- we'll keep only the cob's in use at IPA and delete all other as in the PR

@ipa-nhg: can you please revert (not committ again) the deletion of raws?

**Comment by fmessmer** [comment]
Removing each robot in a separate PullRequest-Set, e.g. PRs each called "remove cob3-1" for cob_calibration_dat, cob_robots and cob_simulation (and where else necessary), could make it easier to later revert the removal by simply undoing the respective PullRequest-Set....

**Comment by floweisshardt** [comment]
is replaced by https://github.com/ipa320/cob_robots/pull/237

**Pull request closed without merging**
