### PR TITLE
moved cob_supported_robots to standalone repo

### PR DESCRIPTION
**Pull request by fmessmer**
merge together with https://github.com/ipa320/cob_supported_robots/pull/1

### CODE REVIEW

**Review by mgruhler — APPROVED** [review]

**Review by NadiaHG — APPROVED** [review]

**Comment by NadiaHG** [comment]
please update the rosinstall files before merge

**Comment by mathias-luedtke** [comment]
@ipa-fxm:  We should merge this now or "revert" https://github.com/ipa320/cob_supported_robots/pull/1
(backup, and resetting to the previous commit)

**Comment by fmessmer** [comment]
finalized in #626

**Comment by fmessmer** [comment]
I'll merge this now as it blocks various "Mutli distro travis" PRs...

rosinstall file is updated in #626

**Pull request merged**
