### PR TITLE
raw3-6 configs

### PR DESCRIPTION
**Pull request by benmaidel**
- added new configs
- startup new nodes on raw3-6

### CODE REVIEW

**Comment by NadiaHG** [comment]
includes https://github.com/ipa320/cob_robots/pull/534/files
FR: OK

**Comment by NadiaHG** [comment]
@ipa-bnm this pull request will overwrite this commit https://github.com/ipa320/cob_robots/pull/534/commits/e15a5cbd37f2786900b91d1d210d266a4e531b91 , which one is the right one?

**Comment by benmaidel** [comment]
@ipa-nhg resolved by merge

**Comment by NadiaHG** [comment]
FR: OK

**Pull request merged**
