### PR TITLE
Sick sensorring

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
please merge together with: https://github.com/ipa320/cob_common/pull/173 and https://github.com/ipa320/cob_calibration_data/pull/91

**Comment by floweisshardt** [comment]
I'd like to keep the asus sensorring for cob4-2. the sick version is only temporary, so please do not merge in cob_robots.
we will soon switch back on cob4-2 to have the asus sensorring again.

**Comment by NadiaHG** [comment]
Created a new branch with the changes for the ipa-cob4-2 account:  https://github.com/ipa-cob4-2/cob_robots/tree/sick_sensorring

We can close this pull request.

**Comment by fmessmer** [comment]
As the feature lives on the cob4-2 specific branch, I'll close this PR

**Pull request closed without merging**
