### PR TITLE
cob4_gripper

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
Please merge with https://github.com/ipa320/cob_calibration_data/pull/76 and https://github.com/ipa320/cob_common/pull/140

**Comment by NadiaHG** [comment]
@ipa-fxm

**Comment by fmessmer** [comment]
Please merge with ipa320!

Please consider comments in [cob_common#140](https://github.com/ipa320/cob_common/pull/140)

There is no `robot_state_publisher` for the grippers! Add

```
<node ns="gripper_left" pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
    <param name="publish_frequency" type="double" value="50.0" />
    <param name="tf_prefix" type="string" value="" />
</node>
<node ns="gripper_right" pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
    <param name="publish_frequency" type="double" value="50.0" />
    <param name="tf_prefix" type="string" value="" />
</node>
```

to cob_controller_configuration_gazebo/launch/robots/default_controllers_cob4-2.launch!

The grippers cannot have a `control_mode_adapter` being started in cob_controller_configuration_gazebo/launch/components/generic_controller_new.launch as they don't support joint_group_velocity_controllers (but those controllers are loaded in the control_mode_adapter). 
@thiagodefreitas has had a similar issue with the base and has a [fix](https://github.com/thiagodefreitas/cob_robots/commit/3acea3213d61107004e1d1431a39f606f16f486c)
However, we should discuss whether the control_mode_adapter should be part of the controller launch files or the driver launch files....@ipa-mdl @ipa-fmw

**Comment by floweisshardt** [comment]
I think it's better to have cob_control_mode_adapter in the controller launch file

**Comment by floweisshardt** [comment]
visual review: OK

**Pull request merged**
