### PR TITLE
Parameter config updates cob4 2

### PR DESCRIPTION
**Pull request by fmessmer**
For now this is a reminder PR...we might want to apply some of the value updates to other yaml files  as well....also the fix in driver.yaml should also be applied to `schunk_robots`

### CODE REVIEW

**Comment by NadiaHG** [comment]
LGTM

**Comment by fmessmer** [comment]
do not merge yet....wait for https://github.com/ipa320/cob_control/pull/51

**Comment by ipa-fxm-mb** [comment]
- collision_check_frames should be collision_check_links in parameters. Additionally change parameter reading: https://github.com/ipa-fxm/cob_control/blob/test_of_feature/cob_twist_controller/src/cob_twist_controller.cpp#L67-L71
- self_collision_frames should be self_collision_links in self_collision YAMLs.
  https://github.com/ipa-fxm/cob_control/blob/test_of_feature/cob_obstacle_distance/src/distance_manager.cpp#L142-L145

**Comment by fmessmer** [comment]
The relevant changes have been applied for cob4-1 as well ass to `schunk_robots` (in https://github.com/ipa320/schunk_robots/pull/56)
https://github.com/ipa320/cob_control/pull/51 is merged!
And @ipa-fxm-mb's [comment](https://github.com/ipa320/cob_robots/pull/322#issuecomment-134250879) is documented [here](https://github.com/ipa320/cob_control/issues/53#issuecomment-134262845)

Thus, I think this PR can be merged. We used this branch during our tests with the robot (Torso/TwistControl Tests).

**Pull request merged**
