### PR TITLE
ros_canopen config for cob4-2 base

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Must be used together with https://github.com/ipa320/cob_driver/pull/258

This patch does **not**
- switch to the new chain
- switch to new base joint names
- remove the old base INI files

It is meant for easy switching between old and new chain. 

@ipa-bnm, @ipa-mig: it should work for the raws, but the values need to be updated based on the INI files

### CODE REVIEW

**Comment by fmessmer** [comment]
please apply also to cob4-1

please help keeping cob4-1 up to date with cob4-2 as cob4-1 is currently used as cob4-2 without arms, i.e. identical hardware platform with configuration for when no arms are attached!

**Comment by benmaidel** [comment]
@ipa-mdl can you please create the config files for the raw's? Me or @ipa-mig doing it will probably take triple the time. thx

**Comment by mathias-luedtke** [comment]
I'd like to test it on cob4-2/1 first, for more than 10 minutes..
After that updating it for the raws should be a piece of cake.

**Comment by mathias-luedtke** [comment]
After a brief look: basically the steer's  `EncOffsetIncr` from the INIs must be copied to the respective `homing_offset` entries.
If you rewired some of the homing switches, `homing_event` must be set to `HomingDigIn`.

Perhaps the controller settings have to be tweak for the raws..
If I remember it correctly https://github.com/ipa320/cob_control/blob/indigo_dev/cob_omni_drive_controller/doc/full_overlay_example.yaml is the config for the raw3-1. Most parameters can be omitted if the URDFs are right.

**Comment by destogl** [comment]
Hi people,

I am interested using this on my r@w3-5. As @ipa-mdl said it should be piece of cake :) Could you give me some directions, so I would have student working on it in the next weeks.

Thx,

Denis

**Comment by floweisshardt** [comment]
tested on cob4-2: OK

**Comment by fmessmer** [comment]
I'll provide an updated PR with configuration for cob4-1

and correct diagnostics_analyzer....

**Comment by mathias-luedtke** [comment]
@destogl: we have resolved some issues, now it works properly with cob4. Of cause we have to run further tests.

We will test it on raw3-3 as soon as we have some time for it.

It would be great if you (or your student) could replicate it with raw3-5.
You will need to:

System set-up:
- overlay cob_driver with https://github.com/ipa320/cob_driver/pull/258
- source overlay https://github.com/ros-industrial/ros_canopen.git
- source overlay: https://github.com/ros-controls/ros_control.git (maybe optional)
- disable peak driver `sudo rmmod pcan`
- activate socketcan `sudo modprobe peak_pci` or `sudo modprobe peak_usb`
- configure socketcan with bitrate 1000000: http://wiki.ros.org/socketcan_interface#Initialize_NIC
- (for permanent change, uninstall or blacklist peak driver, add lines to `/etc/network/interfaces`)

Config (based on #417) :
- in base_driver.yaml:
  - add missing wheel
  - update `homing_offset` (`EncOffsetIncr` in `base/CanCtrl.ini`)
  - check `homing_event`  (`HomingDigIn` in `base/CanCtrl.ini`)
- in base_controller.yaml:
  - add missing wheel or use https://github.com/ipa320/cob_control/blob/indigo_dev/cob_omni_drive_controller/doc/full_overlay_example.yaml
  - updates might be needed according to `base/Platform.ini`

**Comment by floweisshardt** [comment]
I opened a new issue for porting to raws and cob3s. see https://github.com/ipa320/cob_robots/issues/422

**Comment by andreeatulbure** [comment]
Hello,

I and @destogl tried to test the ros_canopen config on the raw3-5. We followed the steps described above by  @ipa-mdl but the wheels of the roboter did not go to zero-position. Do you have any idea why this could happen?

Thanks,
Andreea

**Comment by mathias-luedtke** [comment]
@andreeatulbure: please open a new issue  (or comment in #422)

> Do you have any idea why this could happen?

Something is wrong ;)
For detailed analysis I need:
* config
* service call responses
* console output
* have you set UM=2?

**Pull request merged**
