### PR TITLE
Feature/enable head

### PR DESCRIPTION
**Pull request by fmessmer**
fix https://github.com/ipa320/cob4/issues/349 (for cob4-5 and cob4-7)

 - used @ipa-nhg's test branch from `cob4-5`
 - rebased to latest `indigo_dev` config structure
 - little cob4-5 cleanup and harmonization
 - copied files for cob4-7

first tests (see https://github.com/ipa320/cob_robots/pull/660#issuecomment-297307109) ok

needs more testing
 - knoepkes :+1: 
 - twist control :+1: 
 - longterm :-1:

### CODE REVIEW

**Comment by fmessmer** [comment]
I also get an error during first initialization of head @ipa-mdl @ipa-nhg FYI
```
fxm@cob4-7-b1:~/git/care-o-bot/src/cob_robots/cob_default_robot_config/robots (feature/enable_head)$ rosservice call /head/driver/init 
success: False
message: /u/fxm/git/care-o-bot/src/ros_canopen/canopen_master/src/sdo.cpp(429): Throw in function void canopen::SDOClient::transmitAndWait(const canopen::ObjectDict::Entry&, const canopen::String&, canopen::String*)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<canopen::TimeoutException> >
std::exception::what: SDO
[canopen::tag_objectdict_key*] = 60c2sub1

fxm@cob4-7-b1:~/git/care-o-bot/src/cob_robots/cob_default_robot_config/robots (feature/enable_head)$ rosservice call /head/driver/init 
success: False
message: CAN is not ready
fxm@cob4-7-b1:~/git/care-o-bot/src/cob_robots/cob_default_robot_config/robots (feature/enable_head)$ rosservice call /head/driver/init 
success: False
message: could not reset node '70'
fxm@cob4-7-b1:~/git/care-o-bot/src/cob_robots/cob_default_robot_config/robots (feature/enable_head)$ rosservice call /head/driver/init 
success: True
message: ''
```
after that I can move the head using `rqt_trajectory_controller`

**Comment by mathias-luedtke** [comment]
> I also get an error during first initialization of head 

Every time?

**Comment by fmessmer** [comment]
Doing more tests now - on a fresh `roslaunch cob_bringup robot.launch`:
```
fxm@cob4-7-b1:~$ rosservice call /head/driver/init 
success: False
message: /u/fxm/git/care-o-bot/src/ros_canopen/canopen_master/src/sdo.cpp(429): Throw in function void canopen::SDOClient::transmitAndWait(const canopen::ObjectDict::Entry&, const canopen::String&, canopen::String*)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<canopen::TimeoutException> >
std::exception::what: SDO
[canopen::tag_objectdict_key*] = 60c2sub1

fxm@cob4-7-b1:~$ rosservice call /head/driver/init 
success: True
message: ''
fxm@cob4-7-b1:~$ rosservice call /torso/driver/init 
success: False
message: Transition timeout; Could not enable motor; Transition timeout
```

The `/head/driver/init` error seems to occur every first try and works on the second init.

---

However, for the torso, I'm not able to initialize at all anymore...
@ipa-tif has detected loose cables...he will investigate tomorrow

**Comment by fmessmer** [comment]
tested head with `knoeppkes`:
 - `head_joint_configurations` and `command_gui_buttons` are ok :+1: 
 - but sometimes the head "bails out" with error
 ```
Full Name: /Actuators/Head/head driver: head_3_joint
Component: head driver: head_3_joint
Hardware ID: none
Level: ERROR
Message: Motor has fault; Node has emergency error

error_register: 33
errors: 8611#0
 ```


tested head with `twist_control`
 - works ok...with known limitations of `cob_twist_control`, i.e. `front` position is a singular configuration, thus not a good start position to start tracking a goal :wink:

**Comment by fmessmer** [comment]
torso works again after @ipa-tif checked cabeling

also tested with twist_control :+1: 

~~ControllerInterface for torso should (most likely) also be set to
`controller_interface: cob_twist_controller/ControllerInterfacePosition`~~

**Comment by fmessmer** [comment]
this config is fine for now and can be merged, I'll cross-link the bug `8611#0` to ipa320/cob4#349

**Comment by floweisshardt** [comment]
DO NOT MERGE (yet). We should merge after the head_joint is proven to be robust. Please reopen this PR against ipa320/enable_head

**Comment by fmessmer** [comment]
I rebased to latest `ipa320/indigo_dev` and also pushed to https://github.com/ipa320/cob_robots/tree/feature/enable_head

**Comment by mathias-luedtke** [comment]
> errors: 8611#0

Means position tracking error..

**Comment by fmessmer** [comment]
@ipt-tif made [some mechanical adjustments](https://github.com/ipa320/cob4/issues/349#issuecomment-298626219) to the head
after that `8611` occurred less often when moving to dashboard configurations, e.g. `nod`

however, when moving together with torso - against torso momentum - `8611` still occured a few times
according to @ipa-tif a re-dimensioning of the 2nd head motor might help

also. sometimes `init`/`recover` was not successful on first try...but a retry mostly solved the issues...

**Comment by mathias-luedtke** [comment]
> also. sometimes init/recover was not successful on first try...but a retry mostly solved the issues...

A candump might help.
I guess that the previous driver instance was not shutdown properly, but I am not really sure.

**Review by floweisshardt — APPROVED** [review]
tested on cob4-7: OK, running for 2h without error

**Pull request merged**
