### PR TITLE
skip install space tests

### PR DESCRIPTION
**Pull request by mathias-luedtke**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
There is something wrong with cob_extern.
Perhaps the ExternalProject solution does not cover all cases.

**Comment by fmessmer** [comment]
I saw it...I'm investigating...

**Comment by mathias-luedtke** [comment]
I have tested it locally with `cob_phidgets` and `libphidgets` only, and it worked..

**Comment by fmessmer** [comment]
I also don't see what the problem is...all `libphidgets` headers and libs are where they are supposed to be - for both devel and install....

strange is also, that only kinetic is complaining...
(jade complains because of something different #639)

**Comment by fmessmer** [comment]
let's see how it goes now...

**Comment by mathias-luedtke** [comment]
:tada:

**Comment by mathias-luedtke** [comment]
@ipa-fxm: 
This option can be added safely. Per default the full workspace gets cleaned and rebuilt to install space just to run all installed *.test files.
Currently this means that the install rules do not get checked, but this will change after https://github.com/ros-industrial/industrial_ci/pull/150 was merged

**Review by fmessmer — APPROVED** [review]

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
