### PR TITLE
Indigo release candidate

### PR DESCRIPTION
**Pull request by fmessmer**
I manually fixed the CHANGELOG.rst files

### CODE REVIEW

**Comment by fmessmer** [comment]
I have no idea why travis fails....this PR does not touch any files used in the tests...

**Comment by mgruhler** [comment]
This seems to be a recurring issue https://github.com/ipa-fmw/atf/issues/13, https://github.com/ros-planning/moveit/issues/311, ...

@ipa-fmw any ideas yet?

**Review by mgruhler — APPROVED** [review]

**Comment by mgruhler** [comment]
I have no idea why the push job is failing, but as this branch is far from up-to-date with ipa320, I think we can safely ignore this. Similar issues have been present in other branches as well.

**Comment by fmessmer** [comment]
I opened an issue https://github.com/ipa320/care-o-bot/issues/34 for investigating the travis test behavior

**Pull request merged**
