### PR TITLE
add safe mode for teleop

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
Merge together with: https://github.com/ipa320/cob_command_tools/pull/145

**Comment by NadiaHG** [comment]
@ipa-mig please review

**Comment by NadiaHG** [comment]
Test on cob4-5: OK

**Comment by benmaidel** [comment]
FR: OK

**Comment by mgruhler** [comment]
CR: OK

**Pull request merged**
