### PR TITLE
Fix/diagnostics aggregator

### PR DESCRIPTION
**Pull request by floweisshardt**
superceeds #391 and adds config for all robots

### CODE REVIEW

**Comment by NadiaHG** [comment]
What about cob4-3, cob4-4 and cob4-6?

**Comment by floweisshardt** [comment]
adapted config for cob4-3, cob4-4 and cob4-6. thanks @ipa-nhg

**Comment by NadiaHG** [comment]
CR: OK

**Comment by benmaidel** [comment]
CR: OK

**Comment by fmessmer** [comment]
merging

**Pull request merged**
