### PR TITLE
Parameter config updates

### PR DESCRIPTION
**Pull request by fmessmer**
updates for cartesian_control after ipa-fxm-mb's final presentation on cob4-2 hardware
consistently applied to all robots

### CODE REVIEW

**Comment by floweisshardt** [comment]
FR: OK

**Comment by NadiaHG** [comment]
FR: OK
Tested on the robot?

**Comment by benmaidel** [comment]
FR: :ok:
can not tell anything about the functionality. Just one remark: The pid gains you use, seems to be randomly selected(use the half proportional value as before)?! Is this right?

**Comment by fmessmer** [comment]
The parameter changes are related to feature updates in https://github.com/ipa320/cob_control/pull/63

The PID were originally tuned in simulation but then proofed to be too wild for real hardware...(tuning is still an ongoing process while more and more tests are being performed with the twist_controller on real hardware)

**Comment by fmessmer** [comment]
ToDo:
- add twist_mux input topic for `cob_twist_controller`:`/base/twist_mux/command_syncmm`

**Pull request merged**
