### PR TITLE
Feature/powerball raw3 1

### PR DESCRIPTION
**Pull request by fmessmer**
requires https://github.com/ipa320/cob_common/pull/231

setup for new torso using powerball and ros_canopen
follow-up of #702 

next step towards #703

### CODE REVIEW

**Review by ipa-rmb — DISMISSED** [review]

**Review by ipa-rmb — APPROVED** [review]

**Comment by ipa-rmb** [comment]
prerequisite for #695 .

**Comment by fmessmer** [comment]
@ipa-rmb @ipa-bfb 
can we merge this?
what's the status with the arm? should be done in a new PR, though

**Comment by bbrito** [comment]
@ipa-fxm it looks fine to me. 

The status with the arm its still not sure. The actual P-rob its not working so we are going to change back to the UR arm. This should be the static configuration. All the others will be kept in project specific repos.

**Comment by fmessmer** [comment]
Ok, then I'm going to merge as we tested it on the real robot together with @ipa-rmb 
in order to precede with #703 

Note that the "ur-/gripper-related" stuff has only be commented out...thus, it's easy to re-add once the UR is mounted back on raw3-1

**Pull request merged**
