### PR TITLE
Integrate Softkinetic 

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by benmaidel** [comment]
FR: OK

**Comment by NadiaHG** [comment]
Test on cob4-1 : OK

**Comment by NadiaHG** [comment]
This pull request requires: https://github.com/ipa320/cob_common/pull/188

**Comment by mgruhler** [comment]
@ipa-nhg There is currently a PR open in ipa320/softkinetic#58, which changes how the point clouds are output. have you tested with this? Or what do you think about this?

**Comment by NadiaHG** [comment]
@ipa-mig I didn't test still the https://github.com/ipa320/softkinetic/pull/58, but I will do, thanks :)

@ipa-fmw Travis is not able to compile this pull request, because softkinetic_camera package can not be found, I can add the package to the travis rosinstall file , but we should also release the softkinetic metapackage...

**Comment by floweisshardt** [comment]
@ipa-mig: some weeks ago we disabled travis for the softkinetic repository due to not compiling (required registration for download). If we now add softkinetic to .travis.rosinstall in cob_robots we'll have the same problem. Is there a solution for that? 

That would also be a prerequisit for releasing softkinetic, which is a prerequisit for this PR to be merged!

@ipa-nhg: please do not merge this PR as long as the above issue is not solved

**Comment by NadiaHG** [comment]
I dont think that we will have soon a solution for this issue..
@ipa-fmw what about add softkinetic_camera to cob_substitute?

**Comment by mgruhler** [comment]
@ipa-nhg @ipa-fmw I also only see the `cob_substitute` way. For releasing, I do not see a way how to do that properly...

**Comment by NadiaHG** [comment]
...a possible temporal solution: https://github.com/ipa320/cob_substitute/pull/38

**Comment by benmaidel** [comment]
another possible solution would be: inside CMake check if depthsense sdk is installed, if not plot big warning and compile dummypackage

**Comment by NadiaHG** [comment]
Travis needs https://github.com/ipa320/care-o-bot/pull/27 to compile this pull request

**Comment by floweisshardt** [comment]
https://github.com/ipa320/care-o-bot/pull/27 is merged now, so triggering a new travis run...

**Pull request merged**
