### PR TITLE
[DO NOT MERGE] Backup/kevin cob4 18

### PR DESCRIPTION
**Pull request by floweisshardt**
backup from @ipa340 Kevin from cob4-18

### CODE REVIEW

**Comment by floweisshardt** [comment]
This is just for backup. cob4-18 will be shipped back from ipa340 to ipa320 with default configuration.

cob4-20 and cobo4-23 will be Kevin specific configuration.

**Comment by fmessmer** [comment]
@floweisshardt 
where does this come from? from HW?
then it should get rebased and merged - using the values frim HW of course!

**Comment by fmessmer** [comment]
do we still need this - or only https://github.com/ipa320/cob_robots/pull/802?

**Review by fmessmer — CHANGES_REQUESTED** [review]
@floweisshardt 
where does this come from? from HW?
then it should get rebased and merged - using the values frim HW of course!
I can do that...

do we still need this - or only #802?

**Comment by floweisshardt** [comment]
> do we still need this

no. please keep it open for another 2 weeks until all Kevin hickhack is solved and then we can close this PR without merging

**Comment by floweisshardt** [comment]
not needed anymore. We updated all remaining Kevins this morning at IPA. consolidated PR is https://github.com/ipa320/cob_robots/pull/804

**Pull request closed without merging**
