### PR TITLE
rename canopen driver namespace

### PR DESCRIPTION
**Pull request by floweisshardt**
requested by @ipa-mdl and @ipa-fxm

### CODE REVIEW

**Comment by fmessmer** [comment]
this has effects on the diagnostics aggregation

**Comment by fmessmer** [comment]
I cherry-picked and will fix it in #433

**Comment by fmessmer** [comment]
I don't know why but the diagnostics aggregator is not able to deal with the diagnostics containing e.g. `torso driver` instead of `torso_driver`...whatever, I do (`contains`, `startswith`, `find_prefix` or `regex`) all the torso, base and other diagnostics are not mapped to the respective components anymore but can only be seen in "Others"....I vote for keeping the driver node name as `/component_name/componen_name_driver`....

**Comment by mathias-luedtke** [comment]
some background: the generic analyzer checks on the raw name, including the `/`. Afterwards `/` has  to be substituted, because it is used as group separator in robot monitor (https://github.com/ros/diagnostics/blob/master/diagnostic_aggregator/include/diagnostic_aggregator/status_item.h#L53).

**Pull request closed without merging**
